[tool.poetry]
name = "muscan"
version = "0.1.0"
description = ""
authors = ["Dan Wolf <dcwolf@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
psycopg2 = "^2.9.7"
tinytag = "^1.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

